### ISSUE TITLE
Left column in the profiler window shows internal predicate names

### ISSUE THREAD

**Issue by pmoura** [SWI-Prolog/packages-xpce#17]
The left column in the profiler window shows internal predicate names instead of the names as translated by calling the `user:prolog_predicate_name/2` hook predicate. This issue doesn't happen in the right column, however, as we get the names from calling the hook predicate. An example when using the profiler with a Logtalk goal:

<img width="1143" alt="Screenshot 2020-01-16 at 10 14 48" src="https://user-images.githubusercontent.com/294478/72516180-27d10800-3849-11ea-9110-70bea1dac2f4.png">

As you can see, on the left column, the highlighted predicate (black background) shows the internal predicate name but on the right column the highlighted line (yellow background) shows the user predicate name.

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with SWI-Prolog/swipl-devel@ca3ee4a4a14ec3a8c4053e9b73a5dc8407be9140

**Comment by pmoura** [comment]
Thanks for the quick fix!
