### ISSUE TITLE
xpce: regex ranges integer overflow

### ISSUE THREAD

**Issue by thoger** [SWI-Prolog/packages-xpce#2]
xpce includes regex handling code from tcl.  The same code is also used by postgresql, where it recently got a security fix:

http://www.postgresql.org/about/news/1644/
http://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=3bb3f42f3749d40b8d4de65871e8d828b18d4a45

The problem also affects xpce, albeit its impact is much lower as `assert()` in `addchr()` seems to block overflow.  Abort should still be reproducible with:

~~~
new(S, string('a')),new(R, regex(string('(?i)[\\x0-\\x40000000]'))),send(R, search, S).
~~~

**Comment by JanWielemaker** [comment]
Thanks for noting.  I'm traveling now, so it might take a little while to fix.  XPCE is the not-fool-proof part of Prolog, so this isn't really urgent.

**Comment by JanWielemaker** [comment]
Thanks.   Backported to our copy of the tcl regex libs.  Did not backport cancellation part.
