### ISSUE TITLE
swipl-win.exe is hiding confirm prompt window behind other Windows 10 windows 

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/packages-xpce#27]
Swipl-win is hiding the prompt that asks for example 'Confirm? Save tmp.pl  ok/cancel' when exiting swipl-win. To a user it seems that swipl-win has halted, because the Confirm-window is somewhere buried under other Windows 10 windows.
and [also other windows](https://github.com/SWI-Prolog/swipl-devel/issues/887#issue-1014111625)

**Comment by JanWielemaker** [comment]
Should be fixed with 6d1a3a4addaf3ff83f079bf19bb0c4a1541af052
