### ISSUE TITLE
edit command in Windows 10 duplicates a new editor window when editor window is minimized

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/packages-xpce#28]
In the SWI-Prolog (threaded, 64 bits, version 8.5.6) version that I just installed (this bug did not start with 8.5.6)
1. Start swipl-win.exe by clicking some pl-file
2. ?- edit. 
3.  minimize the XPCE Emacs window
4.  ? edit.

I am expecting an only one editor window that pops-up nicely from the minimized state and gets opened in front of all windows. 
What I get is a multiplying editor window, each time I minimize all editor windows and use edit/0 a new emacs window gets created in the minimized state.  Also one of the editor windows gets opened behing the swipl-win-window.

The XPCE window (from swipl.win Help>XPCE (GUI) Manual ... ) knows how to bring emacs window to front (Tools>Emacs). It does not hide the Emacs window behind other windows as the swipl-win.exe edit/0

Also I now noticed that the XPCE Manual window (the small window with Tools>Emacs) also is duplicating the scratch-window, when scratch-windows are in minimized state.

**Comment by JanWielemaker** [comment]
Should be fixed with 7582e96645c1e8e70f34c1584ed7b82f3f1cb6b4 and c76fcaa4698cd69dab1bed46609825efc18d7e6c
