### ISSUE TITLE
PceEmacs shows a File modified dialog window but nothing was  modifed 

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/packages-xpce#31]
This has been around maybe a week ... maybe two weeks. 

```
Welcome to SWI-Prolog (threaded, 64 bits, version 8.5.20)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- tell('tmp.pl'),writeln('testing.'),told.
true.

?- [tmp].
true.

?- testing.
true.

?- edit(tmp).
true.
%modify file in PceEmacs to testing2.
%ctrl-c ctrl-m
%change back to main window
?- 
% c:/users/pasik/documents/prolog/tmp compiled 0.00 sec, -2 clauses
?- edit(tmp).
true.
?- %now shows a dialog: Modified file ... with buttons to Reload file or Edit buffer
```

**Comment by JanWielemaker** [comment]
Thanks for the detailed report.   Did all the steps as described, but this did not reproduce (Ubunto 22.04, using git HEAD).

**Comment by xpxaxsxi** [comment]
I apologise my bad report, it was missing a operating system. 
Windows 10.

**Comment by xpxaxsxi** [comment]
Maybe this helps. 
```
Welcome to SWI-Prolog (threaded, 64 bits, version 8.5.20)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- 4554 names in 8209 buckets. 2822 shifts
[PCE: Checked 8731 objects]
?- tell('tmp.pl'),writeln('testing.'),told.
true.

?- 4567 names in 8209 buckets. 2854 shifts
[PCE: Checked 9438 objects]
?- edit(tmp).
true.

?- 6010 names in 16421 buckets. 1829 shifts
[PCE warning: @235597790305/emacs_editor: Illegal value in slot editor -dabbrev_mode: nil]
[PCE warning: @235597816492/emacs_prolog_mode: class-variables have not been obtained]
[PCE warning: @235597843632/pixmap: class-variables have not been obtained]
[PCE warning: @235597350963/editor: Illegal value in slot editor -dabbrev_mode: nil]
[PCE: Checked 17104 objects]
[PCE: WARNING: The following type(s) have no associated class:
        [float]
        float
]
```

**Comment by JanWielemaker** [comment]
Thanks.  Doesn't look serious and as xpce is more or less dead code, particularly as it seems we'll get a proper Emacs IDE, I see not much reason to fix this.    Won't be too hard, and if you send a PR I'll merge it :smile:

**Comment by xpxaxsxi** [comment]
To all interested parties: 

V8.5.16 is the first version with this bug https://github.com/SWI-Prolog/swipl-devel/tree/V8.5.16 
These commits seems to have created the bug:

swipl-devel https://github.com/SWI-Prolog/swipl-devel/commit/a3995b48cd6655bd35469b600ba1493cac37426f 
xpce https://github.com/SWI-Prolog/packages-xpce/commit/6b2790bb4094cfbe6bd6e5619ccad7e7f55811a8

I am working on it but ... I can't promise anything.

**Comment by xpxaxsxi** [comment]
This bug was reported again at [Discourse](https://swi-prolog.discourse.group/t/modified-file-dialog-pops-up-when-i-edit-a-file-after-make-0-in-pcemacs-v-9-1-1/6009/11) and  was fixed in https://github.com/SWI-Prolog/packages-xpce/commit/3ee9bb4264407549d9d84b8fa97b7ee63f9bbdff
